msg Creating/resetting admin user ...

$ssh_cmd "php ${app_dir}/bin/magento admin:user:create --admin-user=${user} --admin-password=${password} --admin-email=${email} --admin-firstname=Admin --admin-lastname=Username"
