name: test runner

on:
  push:

env:
  # set a default terminal for various cmds that expect it
  TERM: xterm
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
  SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW: ${{ secrets.SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW }}
  TMATE_AUTHORIZED_KEYS_URL: ${{ secrets.TMATE_AUTHORIZED_KEYS_URL }}
  MAGENTO_CLOUD_CLI_TOKEN: ${{ secrets.MAGENTO_CLOUD_CLI_TOKEN }}

jobs:

  repeatable-tests:
    strategy:
      matrix:
        # sample ref, demo, b2b pids with branches named test-env-for-mce
        # MCE_PROJECT_ID: [xy4itwbmg2khk,a6terwtbk67os,unkfuvjhn2nss]
        MCE_PROJECT_ID: [xy4itwbmg2khk]
    runs-on: ubuntu-latest
    env:
      MCE_PROJECT_ID: ${{ matrix.MCE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: install reqs & deploy
        run: |
          # for connecting to cloud envs without interaction
          mkdir ~/.ssh && chmod 700 ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          ./sh-scripts/install-cli-and-login.sh
      - name: bats tests
        run: |
          exit 1
          ./tests/libs/bats/bin/bats -T ./tests/repeatable-commands.bats
      - name: keep alive to debug
        if: ${{ failure() }}
        uses: PMET-public/action-tmate@master

  # new-branch-tests:
  #   strategy:
  #     matrix:
  #       MCE_PROJECT_ID: []
  #   runs-on: ubuntu-latest